Feature algorythms enhancement
vbozh/featuresques pull request #4
Opened 2021-06-08 14:30 UTC by vbo-acc

Lossless data compression algorithm. 
The idea is to assign variable-length codes to input characters, lengths of the assigned codes are based on the frequencies of corresponding characters.

2021-06-08 14:50 UTC, vbozh requested changes

2021-06-08 14:50 UTC, vbozh commented on src/main/java/NodeCompress.java
> +    public int compare(NodeCompress x, NodeCompress y) {
please, add tests to proceed merge pull request

2021-06-08 15:06 UTC, vbozh requested changes

2021-06-08 15:06 UTC, vbozh commented on src/main/java/NodeCompress.java
> +class ImplementComparator implements Comparator<NodeCompress> {
please, add tests to proceed merge pull request

2021-06-08 15:08 UTC, CK-qa commented on src/main/java/NodeCompress.java
> +// Huffman Coding in Java
Please follow general Code Style rules described in the Guide.md

2021-06-08 15:46 UTC, vbozh commented on src/main/java/NodeCompress.java
> +class ImplementComparator implements Comparator<NodeCompress> {
@vbo-acc

2021-06-09 07:41 UTC, vbozh commented
**fff**

2021-06-09 07:42 UTC, vbozh commented on src/main/java/canal/CleanUpMe.java
> +        this.foo += 1;
increment

2021-06-10 11:12 UTC, vbozh commented
test and delete

2021-07-08 12:17 UTC, merged

2021-08-05 09:53 UTC, vbozh commented on src/main/java/canal/CodeAnalyzeMe.java
> +
single comment

2021-08-05 09:53 UTC, vbozh requested changes
request changes

2021-08-05 09:53 UTC, vbozh commented on src/main/java/canal/CodeAnalyzeMe.java
>      }
start review with a comment